# Copyright (c) 2026, Alexei Znamensky (@russoz)
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

driver:
  name: docker
scenario:
  test_sequence:
    - create
    - converge
    - destroy

# Ensure generated ansible.cfg allows legacy/broken conditionals used by some drivers
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/tests/integration/targets"
  config_options:
    defaults:
      allow_broken_conditionals: True
