---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: "openwrt_x86_64-${OPENWRT_VERSION}"
    image: "openwrt/rootfs:x86_64-${OPENWRT_VERSION}"
    command: sh -c 'mkdir -p /var/lock; sleep infinity'
    pre_build_image: true
scenario:
  test_sequence:
    - create
    - verify
    - destroy
