---
- name: Prepare OpenWRT container (Docker connection only)
  hosts: all
  gather_facts: false
  tasks:
    - name: Create /var/lock directory
      ansible.builtin.command:
        cmd: docker exec {{ inventory_hostname }} mkdir -p /var/lock
      delegate_to: localhost
      changed_when: true
