---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: openwrt_latest
    image: openwrt/rootfs:latest
    command: sleep infinity
    pre_build_image: true
    network_mode: host
provisioner:
  name: ansible
  env:
    ANSIBLE_COLLECTIONS_PATH: "${HOME}/.ansible/collections:/usr/share/ansible/collections:${MOLECULE_SCENARIO_DIRECTORY}/../../../.."
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
