# Copyright (c) 2026, Alexei Znamensky (@russoz)
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Find integration test targets
      ansible.builtin.find:
        paths: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/tests/integration/targets"
        file_type: directory
      delegate_to: localhost
      run_once: true
      register: found_targets

    - name: Include targets
      ansible.builtin.include_role:
        name: "{{ int_test }}"
      loop: "{{ found_targets.files | map(attribute='path') | map('basename') | sort }}"
      loop_control:
        loop_var: int_test
