# (C) 2025 Alexei Znamensky
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

FROM mcr.microsoft.com/devcontainers/python:3.14-bookworm

WORKDIR /workspace

RUN pip install -U pip
