---
- name: Prepare OpenWRT container for SSH access
  hosts: all
  gather_facts: false
  tasks:
    - name: Install dropbear SSH server using docker exec
      ansible.builtin.shell:
        cmd: |
          docker exec {{ inventory_hostname }} sh -c '
            mkdir -p /var/lock
            opkg update
            opkg install dropbear
            passwd -d root
          '
      delegate_to: localhost
      changed_when: true

    - name: Start dropbear in background
      ansible.builtin.shell:
        cmd: docker exec -d {{ inventory_hostname }} /usr/sbin/dropbear -R -F -p 22
      delegate_to: localhost
      changed_when: true

    - name: Wait for SSH to be available
      ansible.builtin.wait_for:
        port: 2222
        host: 127.0.0.1
        delay: 2
        timeout: 30
      delegate_to: localhost
