---
- name: Verify
  hosts: all
  gather_facts: false
  roles:
    - role: community.openwrt.setup
      vars:
        openwrt_install_recommended_packages: false
  tasks:
    - name: Retrieve /etc/os-release
      community.openwrt.slurp:
        src: /etc/os-release
      register: os_release_slurp

    - name: Populate fact os_release
      ansible.builtin.set_fact:
        os_release: >-
          {{
            _os_release_dict.keys() | map('lower')
            | zip(_os_release_dict.values())
            | items2dict(key_name=0, value_name=1)
          }}
      vars:
        _os_release_lines: "{{ os_release_slurp['content'] | b64decode | split('\n') }}"
        _os_release_split: "{{ _os_release_lines | map('regex_search', '^([A-Z_0-9]+)=\"(.*)\"$', '\\1', '\\2') | reject('none') }}"
        _os_release_dict: "{{ dict(_os_release_split) }}"

    - name: Run simple command
      community.openwrt.command:
        cmd: "echo Holy canole,    it\\'s {{ os_release.name }}"
      register: holy_canole
      changed_when: false

    - name: Assert Canole
      ansible.builtin.assert:
        that:
          - holy_canole.stdout.startswith("Holy canole, it's OpenWrt")

    - name: Read UCI
      community.openwrt.uci:
        command: get
        key: dhcp.@dnsmasq[0].domainneeded
      register: uci_dhcp_domainneeded

    - name: Assert UCI can retrieve DHCP config
      ansible.builtin.assert:
        that:
          - uci_dhcp_domainneeded.result == "1"

    - name: Verify opkg is available
      community.openwrt.command:
        cmd: which opkg
      register: opkg_result
      changed_when: false

    - name: Verify recommended packages were installed
      community.openwrt.command:
        cmd: sh -c '[ -x /bin/base64 ] && [ -x /usr/bin/sha1sum ]'
      changed_when: false
