---
# Copyright (c) Ansible Project
# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

- name: "Check for command {{ item.key }}"
  community.openwrt.command:
    cmd: "which {{ item.key | quote }}"
  register: _package
  check_mode: false
  changed_when: false
  failed_when: false

- name: "Install {{ item.value }} to provide {{ item.key }}"
  community.openwrt.opkg:
    name: "{{ item.value }}"
  when: _package.rc != 0
